In [13]:
!pip install pillow

In [14]:
### 불러오기 
from tensorflow.keras.models import load_model
from PIL import Image, ImageOps
import numpy as np

In [15]:
# 학습된 모델 로딩
model = load_model('keras_model.h5')

In [16]:
#예측시킬 이미지 데이터를 넣을 변수 
### ndarray  어레이만드는 함수.      아래 차원은 4차원이다 
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

In [17]:
#예측시킬 이미지 로딩 

In [18]:
image = Image.open('./fox_test.png')

In [19]:
# 예측시킬 이미지를 224x224 크기로 리사이징
size=(224,224)
image=ImageOps.fit(image,size,Image.ANTIALIAS)

C:\Users\smhrd\anaconda3\envs\deep\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
  This is separate from the ipykernel package so we can avoid doing imports until


In [20]:
image_array = np.asarray(image)
image_array

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[246, 246, 246],
        [246, 246, 246],
        [246, 246, 246],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

In [21]:
#정규화 작업(전처리): 학습속도 및 성능 최적화에 도움
normalized_image_array = (image_array.astype(np.float32) / 127.0) - 1
normalized_image_array

array([[[1.007874 , 1.007874 , 1.007874 ],
        [1.007874 , 1.007874 , 1.007874 ],
        [1.007874 , 1.007874 , 1.007874 ],
        ...,
        [1.007874 , 1.007874 , 1.007874 ],
        [1.007874 , 1.007874 , 1.007874 ],
        [1.007874 , 1.007874 , 1.007874 ]],

       [[1.007874 , 1.007874 , 1.007874 ],
        [1.007874 , 1.007874 , 1.007874 ],
        [1.007874 , 1.007874 , 1.007874 ],
        ...,
        [1.007874 , 1.007874 , 1.007874 ],
        [1.007874 , 1.007874 , 1.007874 ],
        [1.007874 , 1.007874 , 1.007874 ]],

       [[1.007874 , 1.007874 , 1.007874 ],
        [1.007874 , 1.007874 , 1.007874 ],
        [1.007874 , 1.007874 , 1.007874 ],
        ...,
        [1.007874 , 1.007874 , 1.007874 ],
        [1.007874 , 1.007874 , 1.007874 ],
        [1.007874 , 1.007874 , 1.007874 ]],

       ...,

       [[0.9370079, 0.9370079, 0.9370079],
        [0.9370079, 0.9370079, 0.9370079],
        [0.9370079, 0.9370079, 0.9370079],
        ...,
        [1.007874 , 1.0078

In [22]:
#불러온 numpy 타입의 이미지를 변수에 대입
data[0] = normalized_image_array

In [23]:
# 예측
prediction = model.predict(data)
print(prediction)

[[9.999987e-01 1.299956e-06]]
